#!/usr/bin/env bash
# kb_bootstrap_customer.sh — create AI-INFO KB folder for a customer
#
# Usage:
#   kb_bootstrap_customer.sh "<Customer Display Name>" [--primary-folder <path>] [--region <region>] [--agents <csv>]
#
# Idempotent: if the AI-INFO folder already exists, updates the registry entry but does not overwrite README/notes.
#
# On success:
#   - Creates <primary>/AI-INFO - DO NOT DELETE/{converted,} and writes README.md, notes.md, memory.md if missing.
#   - Upserts entry in _customer_registry.json.
#   - Prints next steps.

set -euo pipefail

VAULT_ROOT="/Users/joergpietzsch/AI-Vault"
KB_ROOT="$VAULT_ROOT/Claude Folder/Knowledge Base"
REGISTRY="$KB_ROOT/_customer_registry.json"
VENV_PY="$VAULT_ROOT/.venv/bin/python3"
CONVENTIONS_URL="AI-Vault/docs/KB_CONVENTIONS.md"

# ── argument parsing ─────────────────────────────────────────────────────────
DISPLAY_NAME=""
PRIMARY=""
REGION=""
AGENTS="tender"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --primary-folder) PRIMARY="$2"; shift 2 ;;
    --region)         REGION="$2"; shift 2 ;;
    --agents)         AGENTS="$2"; shift 2 ;;
    -h|--help)
      grep -E "^# " "$0" | sed 's/^# //'
      exit 0 ;;
    *)
      if [[ -z "$DISPLAY_NAME" ]]; then
        DISPLAY_NAME="$1"
      else
        echo "Error: unexpected argument: $1" >&2
        exit 2
      fi
      shift ;;
  esac
done

if [[ -z "$DISPLAY_NAME" ]]; then
  echo "Error: customer display name required" >&2
  echo "Usage: $0 \"<Customer Display Name>\" [--primary-folder <path>] [--region <region>] [--agents tender,test,...]" >&2
  exit 2
fi

# ── derive slug ──────────────────────────────────────────────────────────────
SLUG=$(echo "$DISPLAY_NAME" \
  | tr '[:upper:]' '[:lower:]' \
  | sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g')

echo "== Bootstrap customer KB =="
echo "Display name : $DISPLAY_NAME"
echo "Slug         : $SLUG"

# ── infer primary folder if not given ────────────────────────────────────────
if [[ -z "$PRIMARY" ]]; then
  SALES_ROOT="/Users/joergpietzsch/Library/CloudStorage/OneDrive-TTCGlobal/Sales/Customer"
  DELIVERY_ROOT="/Users/joergpietzsch/Library/CloudStorage/OneDrive-TTCGlobal/Delivery"

  # Try exact match under Sales/Customer/<Region>/
  CANDIDATES=$(find "$SALES_ROOT" -maxdepth 2 -type d -iname "$DISPLAY_NAME" 2>/dev/null | head -5)
  if [[ -z "$CANDIDATES" ]]; then
    CANDIDATES=$(find "$DELIVERY_ROOT" -maxdepth 3 -type d -iname "$DISPLAY_NAME" 2>/dev/null | head -5)
  fi

  NUM_CANDIDATES=$(echo "$CANDIDATES" | grep -c . || true)
  if [[ "$NUM_CANDIDATES" == "1" ]]; then
    PRIMARY="$CANDIDATES"
    echo "Primary      : $PRIMARY  (auto-detected)"
  elif [[ "$NUM_CANDIDATES" == "0" ]]; then
    echo "Error: could not auto-detect primary folder. Supply --primary-folder <path>." >&2
    exit 3
  else
    echo "Error: multiple candidate folders found:" >&2
    echo "$CANDIDATES" >&2
    echo "Supply --primary-folder <path> to disambiguate." >&2
    exit 3
  fi
else
  echo "Primary      : $PRIMARY  (supplied)"
fi

if [[ ! -d "$PRIMARY" ]]; then
  echo "Error: primary folder does not exist: $PRIMARY" >&2
  exit 3
fi

# infer region from path if not given
if [[ -z "$REGION" ]]; then
  case "$PRIMARY" in
    *"/Sales/Customer/Middle East/"*) REGION="Middle East" ;;
    *"/Sales/Customer/DACH Region/"*) REGION="DACH Region" ;;
    *"/Sales/Customer/UK/"*)          REGION="UK" ;;
    *"/Delivery/Leapwork/"*)          REGION="South Africa" ;;
    *)                                REGION="Unspecified" ;;
  esac
fi
echo "Region       : $REGION"
echo "Agents       : $AGENTS"

# ── create AI-INFO folder ────────────────────────────────────────────────────
AI_INFO="$PRIMARY/AI-INFO - DO NOT DELETE"
CREATED_NEW=false
if [[ ! -d "$AI_INFO" ]]; then
  mkdir -p "$AI_INFO/converted"
  CREATED_NEW=true
  echo "Created      : $AI_INFO/"
else
  mkdir -p "$AI_INFO/converted"
  echo "Exists       : $AI_INFO/  (idempotent update)"
fi

# Hide the folder from Finder (macOS); reversible with `chflags nohidden`.
# Colleagues on Windows with "Show hidden items" enabled will still see it.
if command -v chflags >/dev/null 2>&1; then
  chflags hidden "$AI_INFO" 2>/dev/null || true
fi

TODAY=$(date +%Y-%m-%d)

# README.md — overwrite protection
if [[ ! -f "$AI_INFO/README.md" ]]; then
  cat > "$AI_INFO/README.md" <<EOF
# AI-INFO — DO NOT DELETE OR RENAME

This folder contains AI reference data for **$DISPLAY_NAME** used by TTC's agent framework.

## What is this?

Shared knowledge base for AI agents working on this customer. Every TTC colleague
with access to this folder can contribute — notes, context, decisions — and AI
agents will pick it up automatically.

## Rules

- **Do not rename this folder.** All agent lookups depend on the exact name
  \`AI-INFO - DO NOT DELETE\`.
- **Do not delete** individual files without checking with the owner (see below).
- **Do edit** \`notes.md\` freely — that's the collaborative space.
- **Do not touch** \`converted/\` by hand — those files are regenerated by the
  converter script.

## Structure

| File/folder | Purpose |
|---|---|
| \`README.md\` | This file. |
| \`notes.md\` | Human-editable customer notes — add anything relevant. |
| \`memory.md\` | Agent session highlights — what AI has learned/decided. |
| \`converted/\` | Generated \`.txt\` KB chunks (read by AI). Don't edit. |
| \`_index.json\` | KB manifest (auto-generated). |

## Metadata

- **Customer:** $DISPLAY_NAME
- **Slug:** \`$SLUG\`
- **Region:** $REGION
- **Created:** $TODAY
- **Primary folder:** \`$PRIMARY\`
- **Responsible:** Joerg Pietzsch (joerg.pietzsch@ttcglobal.com)

## How agents use this

When a TTC agent (Tender / Contracts / Test / TAF) works on this customer, it:

1. Reads \`notes.md\` and \`memory.md\` for context.
2. Searches \`converted/\` for relevant historic documents.
3. Appends session highlights to \`memory.md\` for future sessions.

## Conventions reference

Full rules: \`$CONVENTIONS_URL\`

---
*Managed by TTC agent framework. Do not move or rename.*
EOF
  echo "Wrote        : README.md"
fi

# notes.md — only seed if missing
if [[ ! -f "$AI_INFO/notes.md" ]]; then
  cat > "$AI_INFO/notes.md" <<EOF
# $DISPLAY_NAME — Customer Notes

*Add anything relevant about this customer here. Collaborative — anyone with access can edit.*

## Stakeholders

- TBD

## Current engagement

- TBD

## Key decisions

- $TODAY — Customer KB folder bootstrapped.
EOF
  echo "Wrote        : notes.md"
fi

# memory.md — only seed if missing
if [[ ! -f "$AI_INFO/memory.md" ]]; then
  cat > "$AI_INFO/memory.md" <<EOF
# $DISPLAY_NAME — Agent Memory

*Session highlights appended by agents. Latest entries at the top.*

## $TODAY — Bootstrap

- KB folder created via \`kb_bootstrap_customer.sh\`.
EOF
  echo "Wrote        : memory.md"
fi

# ── upsert into registry ─────────────────────────────────────────────────────
"$VENV_PY" - "$REGISTRY" "$SLUG" "$DISPLAY_NAME" "$REGION" "$PRIMARY" "$AI_INFO" "$AGENTS" "$TODAY" <<'PY'
import json, os, sys
from pathlib import Path

registry_path, slug, display, region, primary, ai_info, agents_csv, today = sys.argv[1:9]
p = Path(registry_path)
data = json.loads(p.read_text()) if p.exists() else {"schema_version": "1.0", "customers": {}}
data.setdefault("customers", {})
existing = data["customers"].get(slug, {})
entry = {
    "display_name": display,
    "region": region,
    "primary_folder": primary,
    "ai_info_folder": ai_info,
    "created": existing.get("created", today),
    "active_agents": sorted(set([a.strip() for a in agents_csv.split(",") if a.strip()])),
    "status": existing.get("status", "active"),
}
if existing.get("notes"):
    entry["notes"] = existing["notes"]
data["customers"][slug] = entry
data["last_updated"] = today
p.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
print(f"Registry     : upserted slug '{slug}' ({'new' if not existing else 'updated'})")
PY

# ── summary ──────────────────────────────────────────────────────────────────
echo
echo "== Done =="
if $CREATED_NEW; then
  echo "Next steps:"
  echo "  1. Review $AI_INFO/README.md"
  echo "  2. Run: kb_refresh_customer.sh \"$DISPLAY_NAME\"  (once available)"
  echo "  3. Edit $AI_INFO/notes.md to seed customer context"
else
  echo "Registry entry updated. No files overwritten."
fi
